name: database_linter

# Controls when the workflow will run
on: [push, fork, workflow_dispatch]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-22.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Install sqlfluff
      - name: Install sqlfluff
        run: pip install sqlfluff

      # Lint SQL files
      - name: Lint SQL files
        run: sqlfluff lint database/scripts/*.sql

